//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Jameak.CursorPagination.Sample;

public partial class KeySetPaginationStrategy : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetPaginationStrategy<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate, KeySetPaginationStrategy.Cursor>, global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursorSerializer<KeySetPaginationStrategy.Cursor>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>
        ApplyPagination(
        global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }
        
        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, afterCursor);
        var filtered = funcs.applyWhereExpr(queryable);
        var ordered = funcs.applyOrderExpr(filtered);
        var limited = funcs.applyTake(ordered);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> applyWhereExpr,
            global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IOrderedQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.ThrowIfPageSizeInvalid(pageSize, checkHasNextPage);

        var whereExpr = PrivateHelper.GetWhereExpr(afterCursor, paginationDirection);
        global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> whereFunc;
        if(whereExpr != null)
        {
            whereFunc = queryable => global::System.Linq.Queryable.Where(queryable, whereExpr);
        }
        else
        {
            whereFunc = queryable => queryable;
        }

        global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IOrderedQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);

        var toTake = pageSize;
        if(checkHasNextPage)
        {
            toTake = PrivateHelper.ComputeToTake(pageSize);
        }

        global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> takeFunc =
            queryable => global::System.Linq.Queryable.Take(queryable, toTake);

        return (whereFunc, orderFunc, takeFunc);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public void PostProcessMaterializedResultInPlace(
        global::System.Collections.Generic.List<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        out bool? hasNextPage)
    {
        Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.KeySetPostProcessResultInPlace(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            out hasNextPage);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CreateCursor(global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate data)
    {
        if (data == null)
        {
            throw new global::System.ArgumentNullException(nameof(data));
        }

        return new Cursor(data.CreatedAt, data.Id);
    }

#region IKeySetCursorSerializer implementation
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CursorFromString(string cursorString)
    {
        if (cursorString == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursorString));
        }

        try
        {
            var decodedString = global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Decode(cursorString);
            return global::System.Text.Json.JsonSerializer.Deserialize<Cursor>(decodedString, options: PrivateHelper.JsonOptions)
              ?? throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Deserializing '{nameof(cursorString)}' argument produced null Cursor object.");
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to decode or deserialize '{nameof(cursorString)}' argument value.", ex);
        }
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public string CursorToString(Cursor cursor)
    {
        if (cursor == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursor));
        }

        try
        {
            var jsonString = global::System.Text.Json.JsonSerializer.Serialize(cursor, options: PrivateHelper.JsonOptions);
            return global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Encode(jsonString);
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to serialize '{nameof(cursor)}' argument value.", ex);
        }
    }
#endregion

    /// <summary>
    /// Source generated Cursor holding the data necessary to paginate the
    /// Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate
    /// type using the fields matching this strategy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public sealed record Cursor : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursor
    {
        public global::System.DateTime CreatedAt { get; init; }
        public int Id { get; init; }

        public Cursor(global::System.DateTime CreatedAt, int Id)
        {
            this.CreatedAt = CreatedAt;
            this.Id = Id;
        }
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal const char CursorElemSeparator = ';';

    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> ApplyOrderBy(
        global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.CreatedAt));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.Id));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.CreatedAt));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.Id));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }

    internal static global::System.Linq.Expressions.Expression<global::System.Func<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate, bool>>? GetWhereExpr(
        KeySetPaginationStrategy.Cursor? cursor,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        if(cursor == null)
        {
            return null;
        }

        var CreatedAtValue = cursor.CreatedAt;
        var IdValue = cursor.Id;

        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                return obj =>
                    obj.CreatedAt! <= CreatedAtValue!
                    && (
                        (obj.CreatedAt! < CreatedAtValue!) ||
                        (obj.CreatedAt! == CreatedAtValue! && obj.Id! > IdValue!)
                    );
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                return obj =>
                    obj.CreatedAt! >= CreatedAtValue!
                    && (
                        (obj.CreatedAt! > CreatedAtValue!) ||
                        (obj.CreatedAt! == CreatedAtValue! && obj.Id! < IdValue!)
                    );
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
#region IKeySetCursorSerializer De-/serialization methods
    internal static global::System.Text.Json.JsonSerializerOptions JsonOptions { get; } = InitializeJsonOptions();

    private static global::System.Text.Json.JsonSerializerOptions InitializeJsonOptions()
    {
        var options = new global::System.Text.Json.JsonSerializerOptions
        {
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals,
            PropertyNamingPolicy = new CursorHiddenNamePolicy(),
        };
        
        options.Converters.Add(new DateTimeRoundtripJsonConverter());

        return options;
    }
#endregion
}

file class CursorHiddenNamePolicy : global::System.Text.Json.JsonNamingPolicy
{
    public override string ConvertName(string name)
    {
        return name switch
        {
            nameof(KeySetPaginationStrategy.Cursor.CreatedAt) => "0",
            nameof(KeySetPaginationStrategy.Cursor.Id) => "1",
            _ => throw new global::System.NotImplementedException($"Unhandled name: {name}"),
        };
    }
}

file class DateTimeRoundtripJsonConverter : global::System.Text.Json.Serialization.JsonConverter<global::System.DateTime>
{
    public override global::System.DateTime Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
    {
        var stringValue = reader.GetString() ?? throw new global::Jameak.CursorPagination.Abstractions.Exceptions.DateTimeRoundtripJsonException("Cannot deserialize 'null' json value into DateTime object.");
        var split = stringValue.Split(':');

        if (split.Length != 2)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.DateTimeRoundtripJsonException("String to convert into DateTime is invalid.");
        }

        try
        {
            return new global::System.DateTime(long.Parse(split[0], global::System.Globalization.CultureInfo.InvariantCulture), split[1] switch
            {
                "L" => global::System.DateTimeKind.Local,
                "UTC" => global::System.DateTimeKind.Utc,
                "Un" => global::System.DateTimeKind.Unspecified,
                _ => throw new global::System.NotSupportedException($"Unhandled serialized kind: {split[1]}"),
            });
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.DateTimeRoundtripJsonException("String to convert into DateTime is invalid.", ex);
        }
    }

    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, global::System.DateTime value, global::System.Text.Json.JsonSerializerOptions options)
    {
        var stringValue = value.Ticks + ":" + value.Kind switch
        {
            global::System.DateTimeKind.Local => "L",
            global::System.DateTimeKind.Utc => "UTC",
            global::System.DateTimeKind.Unspecified => "Un",
            _ => throw new global::System.NotSupportedException($"Unhandled kind: {value.Kind}"),
        };

        writer.WriteStringValue(stringValue);
    }
}
