//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Jameak.CursorPagination.Sample;

public partial class OffsetPaginationStrategy : global::Jameak.CursorPagination.Abstractions.OffsetPagination.IOffsetPaginationStrategy<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>
        ApplyPagination(
        global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor? cursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }

        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, cursor);
        var ordered = funcs.applyOrderExpr(queryable);
        var skipped = funcs.applySkip(ordered);
        var limited = funcs.applyTake(skipped);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IOrderedQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> applySkip,
            global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor? cursor)
    {
        global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.ThrowIfPageSizeInvalid(pageSize, checkHasNextPage);

        global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IOrderedQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);

        global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> skipFunc;
        if(cursor != null)
        {
            var skipValue = cursor.Skip;
            skipFunc = queryable => global::System.Linq.Queryable.Skip(queryable, skipValue);
        }
        else
        {
            skipFunc = queryable => queryable;
        }

        var toTake = pageSize;
        if(checkHasNextPage)
        {
            toTake = PrivateHelper.ComputeToTake(pageSize);
        }

        global::System.Func<global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>, global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate>> takeFunc =
            queryable => global::System.Linq.Queryable.Take(queryable, toTake);

        return (orderFunc, skipFunc, takeFunc);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Collections.Generic.IEnumerable<global::Jameak.CursorPagination.Abstractions.RowData<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate, global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor>>
        PostProcessMaterializedResult(
        global::System.Collections.Generic.List<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor? cursor,
        out bool? hasNextPage)
    {
        return Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.OffsetPostProcessResult(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            cursor,
            out hasNextPage);
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> ApplyOrderBy(
        global::System.Linq.IQueryable<global::Jameak.CursorPagination.Sample.ResponseModels.DtoTypeToPaginate> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.CreatedAt));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.Id));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.CreatedAt));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.Id));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
}
