//HintName: TestStrategy_K.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TestNamespace;

public partial class TestStrategy : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetPaginationStrategy<global::TestNamespace.TestInput, TestStrategy.Cursor>, global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursorSerializer<TestStrategy.Cursor>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::TestNamespace.TestInput>
        ApplyPagination(
        global::System.Linq.IQueryable<global::TestNamespace.TestInput> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }
        
        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, afterCursor);
        var filtered = funcs.applyWhereExpr(queryable);
        var ordered = funcs.applyOrderExpr(filtered);
        var limited = funcs.applyTake(ordered);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> applyWhereExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.ThrowIfPageSizeInvalid(pageSize, checkHasNextPage);

        var whereExpr = PrivateHelper.GetWhereExpr(afterCursor, paginationDirection);
        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> whereFunc;
        if(whereExpr != null)
        {
            whereFunc = queryable => global::System.Linq.Queryable.Where(queryable, whereExpr);
        }
        else
        {
            whereFunc = queryable => queryable;
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);

        var toTake = pageSize;
        if(checkHasNextPage)
        {
            toTake = PrivateHelper.ComputeToTake(pageSize);
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> takeFunc =
            queryable => global::System.Linq.Queryable.Take(queryable, toTake);

        return (whereFunc, orderFunc, takeFunc);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public void PostProcessMaterializedResultInPlace(
        global::System.Collections.Generic.List<global::TestNamespace.TestInput> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        out bool? hasNextPage)
    {
        Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.KeySetPostProcessResultInPlace(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            out hasNextPage);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CreateCursor(global::TestNamespace.TestInput data)
    {
        if (data == null)
        {
            throw new global::System.ArgumentNullException(nameof(data));
        }

        return new Cursor(data.LongProp, data.StringProp, data.IntProp);
    }

#region IKeySetCursorSerializer implementation
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CursorFromString(string cursorString)
    {
        if (cursorString == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursorString));
        }

        try
        {
            var decodedString = global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Decode(cursorString);
            return global::System.Text.Json.JsonSerializer.Deserialize<Cursor>(decodedString, options: PrivateHelper.JsonOptions)
              ?? throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Deserializing '{nameof(cursorString)}' argument produced null Cursor object.");
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to decode or deserialize '{nameof(cursorString)}' argument value.", ex);
        }
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public string CursorToString(Cursor cursor)
    {
        if (cursor == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursor));
        }

        try
        {
            var jsonString = global::System.Text.Json.JsonSerializer.Serialize(cursor, options: PrivateHelper.JsonOptions);
            return global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Encode(jsonString);
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to serialize '{nameof(cursor)}' argument value.", ex);
        }
    }
#endregion

    /// <summary>
    /// Source generated Cursor holding the data necessary to paginate the
    /// TestNamespace.TestInput
    /// type using the fields matching this strategy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public sealed record Cursor : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursor
    {
        public long LongProp { get; init; }
        public string StringProp { get; init; }
        public int IntProp { get; init; }

        public Cursor(long LongProp, string StringProp, int IntProp)
        {
            this.LongProp = LongProp;
            this.StringProp = StringProp;
            this.IntProp = IntProp;
        }
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal const char CursorElemSeparator = ';';

    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput> ApplyOrderBy(
        global::System.Linq.IQueryable<global::TestNamespace.TestInput> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.LongProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.StringProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.IntProp));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.LongProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.StringProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.IntProp));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }

    internal static global::System.Linq.Expressions.Expression<global::System.Func<global::TestNamespace.TestInput, bool>>? GetWhereExpr(
        TestStrategy.Cursor? cursor,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        if(cursor == null)
        {
            return null;
        }

        var LongPropValue = cursor.LongProp;
        var StringPropValue = cursor.StringProp;
        var IntPropValue = cursor.IntProp;

        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                return obj =>
                    obj.LongProp! >= LongPropValue!
                    && (
                        (obj.LongProp! > LongPropValue!) ||
                        (obj.LongProp! == LongPropValue! && obj.StringProp!.CompareTo(StringPropValue!) > 0) ||
                        (obj.LongProp! == LongPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.IntProp! < IntPropValue!)
                    );
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                return obj =>
                    obj.LongProp! <= LongPropValue!
                    && (
                        (obj.LongProp! < LongPropValue!) ||
                        (obj.LongProp! == LongPropValue! && obj.StringProp!.CompareTo(StringPropValue!) < 0) ||
                        (obj.LongProp! == LongPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.IntProp! > IntPropValue!)
                    );
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
#region IKeySetCursorSerializer De-/serialization methods
    internal static global::System.Text.Json.JsonSerializerOptions JsonOptions { get; } = InitializeJsonOptions();

    private static global::System.Text.Json.JsonSerializerOptions InitializeJsonOptions()
    {
        var options = new global::System.Text.Json.JsonSerializerOptions
        {
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals,
            PropertyNamingPolicy = new CursorHiddenNamePolicy(),
        };
        
        return options;
    }
#endregion
}

file class CursorHiddenNamePolicy : global::System.Text.Json.JsonNamingPolicy
{
    public override string ConvertName(string name)
    {
        return name switch
        {
            nameof(TestStrategy.Cursor.LongProp) => "0",
            nameof(TestStrategy.Cursor.StringProp) => "1",
            nameof(TestStrategy.Cursor.IntProp) => "2",
            _ => throw new global::System.NotImplementedException($"Unhandled name: {name}"),
        };
    }
}
