//HintName: TestStrategy_K.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TestNamespace;

public partial class TestStrategy : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetPaginationStrategy<global::TestNamespace.TestInput, TestStrategy.Cursor>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::TestNamespace.TestInput>
        ApplyPagination(
        global::System.Linq.IQueryable<global::TestNamespace.TestInput> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }
        
        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, afterCursor);
        var filtered = funcs.applyWhereExpr(queryable);
        var ordered = funcs.applyOrderExpr(filtered);
        var limited = funcs.applyTake(ordered);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> applyWhereExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.ThrowIfPageSizeInvalid(pageSize, checkHasNextPage);

        var whereExpr = PrivateHelper.GetWhereExpr(afterCursor, paginationDirection);
        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> whereFunc;
        if(whereExpr != null)
        {
            whereFunc = queryable => global::System.Linq.Queryable.Where(queryable, whereExpr);
        }
        else
        {
            whereFunc = queryable => queryable;
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);

        var toTake = pageSize;
        if(checkHasNextPage)
        {
            toTake = PrivateHelper.ComputeToTake(pageSize);
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> takeFunc =
            queryable => global::System.Linq.Queryable.Take(queryable, toTake);

        return (whereFunc, orderFunc, takeFunc);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public void PostProcessMaterializedResultInPlace(
        global::System.Collections.Generic.List<global::TestNamespace.TestInput> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        out bool? hasNextPage)
    {
        Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.KeySetPostProcessResultInPlace(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            out hasNextPage);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CreateCursor(global::TestNamespace.TestInput data)
    {
        if (data == null)
        {
            throw new global::System.ArgumentNullException(nameof(data));
        }

        return new Cursor(data.PublicField);
    }


    /// <summary>
    /// Source generated Cursor holding the data necessary to paginate the
    /// TestNamespace.TestInput
    /// type using the fields matching this strategy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public sealed record Cursor : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursor
    {
        public string PublicField { get; init; }

        public Cursor(string PublicField)
        {
            this.PublicField = PublicField;
        }
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal const char CursorElemSeparator = ';';

    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput> ApplyOrderBy(
        global::System.Linq.IQueryable<global::TestNamespace.TestInput> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.PublicField));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.PublicField));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }

    internal static global::System.Linq.Expressions.Expression<global::System.Func<global::TestNamespace.TestInput, bool>>? GetWhereExpr(
        TestStrategy.Cursor? cursor,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        if(cursor == null)
        {
            return null;
        }

        var PublicFieldValue = cursor.PublicField;

        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                return obj =>
                    obj.PublicField!.CompareTo(PublicFieldValue!) > 0;
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                return obj =>
                    obj.PublicField!.CompareTo(PublicFieldValue!) < 0;
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
}
