//HintName: TestKeysetPaginationStrategy_K.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TestNamespace;

public partial class TestKeysetPaginationStrategy : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetPaginationStrategy<global::TestNamespace.TestInput, TestKeysetPaginationStrategy.Cursor>, global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursorSerializer<TestKeysetPaginationStrategy.Cursor>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::TestNamespace.TestInput>
        ApplyPagination(
        global::System.Linq.IQueryable<global::TestNamespace.TestInput> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }
        
        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, afterCursor);
        var filtered = funcs.applyWhereExpr(queryable);
        var ordered = funcs.applyOrderExpr(filtered);
        var limited = funcs.applyTake(ordered);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> applyWhereExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.ThrowIfPageSizeInvalid(pageSize, checkHasNextPage);

        var whereExpr = PrivateHelper.GetWhereExpr(afterCursor, paginationDirection);
        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> whereFunc;
        if(whereExpr != null)
        {
            whereFunc = queryable => global::System.Linq.Queryable.Where(queryable, whereExpr);
        }
        else
        {
            whereFunc = queryable => queryable;
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);

        var toTake = pageSize;
        if(checkHasNextPage)
        {
            toTake = PrivateHelper.ComputeToTake(pageSize);
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.TestInput>, global::System.Linq.IQueryable<global::TestNamespace.TestInput>> takeFunc =
            queryable => global::System.Linq.Queryable.Take(queryable, toTake);

        return (whereFunc, orderFunc, takeFunc);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public void PostProcessMaterializedResultInPlace(
        global::System.Collections.Generic.List<global::TestNamespace.TestInput> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        out bool? hasNextPage)
    {
        Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.KeySetPostProcessResultInPlace(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            out hasNextPage);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CreateCursor(global::TestNamespace.TestInput data)
    {
        if (data == null)
        {
            throw new global::System.ArgumentNullException(nameof(data));
        }

        return new Cursor(data.BoolProp, data.ByteProp, data.DateTimeProp, data.DateTimeOffsetProp, data.DecimalProp, data.DoubleProp, data.FloatProp, data.GuidProp, data.IntProp, data.LongProp, data.SbyteProp, data.ShortProp, data.StringProp, data.UshortProp, data.UintProp, data.UlongProp);
    }

#region IKeySetCursorSerializer implementation
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CursorFromString(string cursorString)
    {
        if (cursorString == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursorString));
        }

        try
        {
            var decodedString = global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Decode(cursorString);
            return global::System.Text.Json.JsonSerializer.Deserialize<Cursor>(decodedString, options: PrivateHelper.JsonOptions)
              ?? throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Deserializing '{nameof(cursorString)}' argument produced null Cursor object.");
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to decode or deserialize '{nameof(cursorString)}' argument value.", ex);
        }
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public string CursorToString(Cursor cursor)
    {
        if (cursor == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursor));
        }

        try
        {
            var jsonString = global::System.Text.Json.JsonSerializer.Serialize(cursor, options: PrivateHelper.JsonOptions);
            return global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Encode(jsonString);
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to serialize '{nameof(cursor)}' argument value.", ex);
        }
    }
#endregion

    /// <summary>
    /// Source generated Cursor holding the data necessary to paginate the
    /// TestNamespace.TestInput
    /// type using the fields matching this strategy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public sealed record Cursor : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursor
    {
        public bool BoolProp { get; init; }
        public byte ByteProp { get; init; }
        public global::System.DateTime DateTimeProp { get; init; }
        public global::System.DateTimeOffset DateTimeOffsetProp { get; init; }
        public decimal DecimalProp { get; init; }
        public double DoubleProp { get; init; }
        public float FloatProp { get; init; }
        public global::System.Guid GuidProp { get; init; }
        public int IntProp { get; init; }
        public long LongProp { get; init; }
        public sbyte SbyteProp { get; init; }
        public short ShortProp { get; init; }
        public string StringProp { get; init; }
        public ushort UshortProp { get; init; }
        public uint UintProp { get; init; }
        public ulong UlongProp { get; init; }

        public Cursor(bool BoolProp, byte ByteProp, global::System.DateTime DateTimeProp, global::System.DateTimeOffset DateTimeOffsetProp, decimal DecimalProp, double DoubleProp, float FloatProp, global::System.Guid GuidProp, int IntProp, long LongProp, sbyte SbyteProp, short ShortProp, string StringProp, ushort UshortProp, uint UintProp, ulong UlongProp)
        {
            this.BoolProp = BoolProp;
            this.ByteProp = ByteProp;
            this.DateTimeProp = DateTimeProp;
            this.DateTimeOffsetProp = DateTimeOffsetProp;
            this.DecimalProp = DecimalProp;
            this.DoubleProp = DoubleProp;
            this.FloatProp = FloatProp;
            this.GuidProp = GuidProp;
            this.IntProp = IntProp;
            this.LongProp = LongProp;
            this.SbyteProp = SbyteProp;
            this.ShortProp = ShortProp;
            this.StringProp = StringProp;
            this.UshortProp = UshortProp;
            this.UintProp = UintProp;
            this.UlongProp = UlongProp;
        }
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal const char CursorElemSeparator = ';';

    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::TestNamespace.TestInput> ApplyOrderBy(
        global::System.Linq.IQueryable<global::TestNamespace.TestInput> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.BoolProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.ByteProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.DateTimeProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.DateTimeOffsetProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.DecimalProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.DoubleProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.FloatProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.GuidProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.IntProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.LongProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.SbyteProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.ShortProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.StringProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.UshortProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.UintProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.UlongProp));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.BoolProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.ByteProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.DateTimeProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.DateTimeOffsetProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.DecimalProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.DoubleProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.FloatProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.GuidProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.IntProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.LongProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.SbyteProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.ShortProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.StringProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.UshortProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.UintProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.UlongProp));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }

    internal static global::System.Linq.Expressions.Expression<global::System.Func<global::TestNamespace.TestInput, bool>>? GetWhereExpr(
        TestKeysetPaginationStrategy.Cursor? cursor,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        if(cursor == null)
        {
            return null;
        }

        var BoolPropValue = cursor.BoolProp;
        var BytePropValue = cursor.ByteProp;
        var DateTimePropValue = cursor.DateTimeProp;
        var DateTimeOffsetPropValue = cursor.DateTimeOffsetProp;
        var DecimalPropValue = cursor.DecimalProp;
        var DoublePropValue = cursor.DoubleProp;
        var FloatPropValue = cursor.FloatProp;
        var GuidPropValue = cursor.GuidProp;
        var IntPropValue = cursor.IntProp;
        var LongPropValue = cursor.LongProp;
        var SbytePropValue = cursor.SbyteProp;
        var ShortPropValue = cursor.ShortProp;
        var StringPropValue = cursor.StringProp;
        var UshortPropValue = cursor.UshortProp;
        var UintPropValue = cursor.UintProp;
        var UlongPropValue = cursor.UlongProp;

        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                return obj =>
                    obj.BoolProp!.CompareTo(BoolPropValue!) >= 0
                    && (
                        (obj.BoolProp!.CompareTo(BoolPropValue!) > 0) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! > BytePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! > DateTimePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! > DateTimeOffsetPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! > DecimalPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! > DoublePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! > FloatPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) > 0) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! > IntPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! > LongPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! > SbytePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! > ShortPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) > 0) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.UshortProp! > UshortPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.UshortProp! == UshortPropValue! && obj.UintProp! > UintPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.UshortProp! == UshortPropValue! && obj.UintProp! == UintPropValue! && obj.UlongProp! > UlongPropValue!)
                    );
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                return obj =>
                    obj.BoolProp!.CompareTo(BoolPropValue!) <= 0
                    && (
                        (obj.BoolProp!.CompareTo(BoolPropValue!) < 0) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! < BytePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! < DateTimePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! < DateTimeOffsetPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! < DecimalPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! < DoublePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! < FloatPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) < 0) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! < IntPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! < LongPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! < SbytePropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! < ShortPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) < 0) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.UshortProp! < UshortPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.UshortProp! == UshortPropValue! && obj.UintProp! < UintPropValue!) ||
                        (obj.BoolProp!.CompareTo(BoolPropValue!) == 0 && obj.ByteProp! == BytePropValue! && obj.DateTimeProp! == DateTimePropValue! && obj.DateTimeOffsetProp! == DateTimeOffsetPropValue! && obj.DecimalProp! == DecimalPropValue! && obj.DoubleProp! == DoublePropValue! && obj.FloatProp! == FloatPropValue! && obj.GuidProp!.CompareTo(GuidPropValue!) == 0 && obj.IntProp! == IntPropValue! && obj.LongProp! == LongPropValue! && obj.SbyteProp! == SbytePropValue! && obj.ShortProp! == ShortPropValue! && obj.StringProp!.CompareTo(StringPropValue!) == 0 && obj.UshortProp! == UshortPropValue! && obj.UintProp! == UintPropValue! && obj.UlongProp! < UlongPropValue!)
                    );
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
#region IKeySetCursorSerializer De-/serialization methods
    internal static global::System.Text.Json.JsonSerializerOptions JsonOptions { get; } = InitializeJsonOptions();

    private static global::System.Text.Json.JsonSerializerOptions InitializeJsonOptions()
    {
        var options = new global::System.Text.Json.JsonSerializerOptions
        {
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals,
            PropertyNamingPolicy = new CursorHiddenNamePolicy(),
        };
        
        options.Converters.Add(new DateTimeRoundtripJsonConverter());

        return options;
    }
#endregion
}

file class CursorHiddenNamePolicy : global::System.Text.Json.JsonNamingPolicy
{
    public override string ConvertName(string name)
    {
        return name switch
        {
            nameof(TestKeysetPaginationStrategy.Cursor.BoolProp) => "0",
            nameof(TestKeysetPaginationStrategy.Cursor.ByteProp) => "1",
            nameof(TestKeysetPaginationStrategy.Cursor.DateTimeProp) => "2",
            nameof(TestKeysetPaginationStrategy.Cursor.DateTimeOffsetProp) => "3",
            nameof(TestKeysetPaginationStrategy.Cursor.DecimalProp) => "4",
            nameof(TestKeysetPaginationStrategy.Cursor.DoubleProp) => "5",
            nameof(TestKeysetPaginationStrategy.Cursor.FloatProp) => "6",
            nameof(TestKeysetPaginationStrategy.Cursor.GuidProp) => "7",
            nameof(TestKeysetPaginationStrategy.Cursor.IntProp) => "8",
            nameof(TestKeysetPaginationStrategy.Cursor.LongProp) => "9",
            nameof(TestKeysetPaginationStrategy.Cursor.SbyteProp) => "10",
            nameof(TestKeysetPaginationStrategy.Cursor.ShortProp) => "11",
            nameof(TestKeysetPaginationStrategy.Cursor.StringProp) => "12",
            nameof(TestKeysetPaginationStrategy.Cursor.UshortProp) => "13",
            nameof(TestKeysetPaginationStrategy.Cursor.UintProp) => "14",
            nameof(TestKeysetPaginationStrategy.Cursor.UlongProp) => "15",
            _ => throw new global::System.NotImplementedException($"Unhandled name: {name}"),
        };
    }
}

file class DateTimeRoundtripJsonConverter : global::System.Text.Json.Serialization.JsonConverter<global::System.DateTime>
{
    public override global::System.DateTime Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)
    {
        var stringValue = reader.GetString() ?? throw new global::Jameak.CursorPagination.Abstractions.Exceptions.DateTimeRoundtripJsonException("Cannot deserialize 'null' json value into DateTime object.");
        var split = stringValue.Split(':');

        if (split.Length != 2)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.DateTimeRoundtripJsonException("String to convert into DateTime is invalid.");
        }

        try
        {
            return new global::System.DateTime(long.Parse(split[0], global::System.Globalization.CultureInfo.InvariantCulture), split[1] switch
            {
                "L" => global::System.DateTimeKind.Local,
                "UTC" => global::System.DateTimeKind.Utc,
                "Un" => global::System.DateTimeKind.Unspecified,
                _ => throw new global::System.NotSupportedException($"Unhandled serialized kind: {split[1]}"),
            });
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.DateTimeRoundtripJsonException("String to convert into DateTime is invalid.", ex);
        }
    }

    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, global::System.DateTime value, global::System.Text.Json.JsonSerializerOptions options)
    {
        var stringValue = value.Ticks + ":" + value.Kind switch
        {
            global::System.DateTimeKind.Local => "L",
            global::System.DateTimeKind.Utc => "UTC",
            global::System.DateTimeKind.Unspecified => "Un",
            _ => throw new global::System.NotSupportedException($"Unhandled kind: {value.Kind}"),
        };

        writer.WriteStringValue(stringValue);
    }
}
