//HintName: TestStrategyOffset_O.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TestNamespace;

internal partial class TestStrategyOffset : global::Jameak.CursorPagination.Abstractions.OffsetPagination.IOffsetPaginationStrategy<global::TestNamespace.Level1>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::TestNamespace.Level1>
        ApplyPagination(
        global::System.Linq.IQueryable<global::TestNamespace.Level1> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor? cursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }

        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, cursor);
        var ordered = funcs.applyOrderExpr(queryable);
        var skipped = funcs.applySkip(ordered);
        var limited = funcs.applyTake(skipped);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.Level1>, global::System.Linq.IOrderedQueryable<global::TestNamespace.Level1>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.Level1>, global::System.Linq.IQueryable<global::TestNamespace.Level1>> applySkip,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.Level1>, global::System.Linq.IQueryable<global::TestNamespace.Level1>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor? cursor)
    {
        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.Level1>, global::System.Linq.IOrderedQueryable<global::TestNamespace.Level1>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);
        
        return Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.OffsetBuildPaginationMethods(
            pageSize,
            checkHasNextPage,
            orderFunc,
            cursor);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Collections.Generic.IEnumerable<global::Jameak.CursorPagination.Abstractions.RowData<global::TestNamespace.Level1, global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor>>
        PostProcessMaterializedResult(
        global::System.Collections.Generic.List<global::TestNamespace.Level1> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        global::Jameak.CursorPagination.Abstractions.OffsetPagination.OffsetCursor? cursor,
        out bool? hasNextPage)
    {
        return Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.OffsetPostProcessResult(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            cursor,
            out hasNextPage);
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::TestNamespace.Level1> ApplyOrderBy(
        global::System.Linq.IQueryable<global::TestNamespace.Level1> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.Nested.NullableNested.ValueTypeNested.NullableValueTypeNested!.Value.StringProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.Nested.NullableNested.ValueTypeNested.NullableValueTypeNested!.Value.IntProp));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.Nested.NullableNested.ValueTypeNested.NullableValueTypeNested!.Value.StringProp));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.Nested.NullableNested.ValueTypeNested.NullableValueTypeNested!.Value.IntProp));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
}
