//HintName: protected_K.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Jameak.CursorPagination.SourceGenerator source generator
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace TestNamespace;

internal partial class @protected : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetPaginationStrategy<global::TestNamespace.@event, @protected.Cursor>, global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursorSerializer<@protected.Cursor>
{
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public global::System.Linq.IQueryable<global::TestNamespace.@event>
        ApplyPagination(
        global::System.Linq.IQueryable<global::TestNamespace.@event> queryable,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        if (queryable == null)
        {
            throw new global::System.ArgumentNullException(nameof(queryable));
        }
        
        var funcs = BuildPaginationMethods(pageSize, checkHasNextPage, paginationDirection, afterCursor);
        var filtered = funcs.applyWhereExpr(queryable);
        var ordered = funcs.applyOrderExpr(filtered);
        var limited = funcs.applyTake(ordered);
        return limited;
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public (global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.@event>, global::System.Linq.IQueryable<global::TestNamespace.@event>> applyWhereExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.@event>, global::System.Linq.IOrderedQueryable<global::TestNamespace.@event>> applyOrderExpr,
            global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.@event>, global::System.Linq.IQueryable<global::TestNamespace.@event>> applyTake)
        BuildPaginationMethods(
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        Cursor? afterCursor)
    {
        global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.ThrowIfPageSizeInvalid(pageSize, checkHasNextPage);

        var whereExpr = PrivateHelper.GetWhereExpr(afterCursor, paginationDirection);
        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.@event>, global::System.Linq.IQueryable<global::TestNamespace.@event>> whereFunc;
        if(whereExpr != null)
        {
            whereFunc = queryable => global::System.Linq.Queryable.Where(queryable, whereExpr);
        }
        else
        {
            whereFunc = queryable => queryable;
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.@event>, global::System.Linq.IOrderedQueryable<global::TestNamespace.@event>> orderFunc =
            queryable => PrivateHelper.ApplyOrderBy(queryable, paginationDirection);

        var toTake = pageSize;
        if(checkHasNextPage)
        {
            toTake = PrivateHelper.ComputeToTake(pageSize);
        }

        global::System.Func<global::System.Linq.IQueryable<global::TestNamespace.@event>, global::System.Linq.IQueryable<global::TestNamespace.@event>> takeFunc =
            queryable => global::System.Linq.Queryable.Take(queryable, toTake);

        return (whereFunc, orderFunc, takeFunc);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public void PostProcessMaterializedResultInPlace(
        global::System.Collections.Generic.List<global::TestNamespace.@event> materializedResult,
        int pageSize,
        bool checkHasNextPage,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection,
        out bool? hasNextPage)
    {
        Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.KeySetPostProcessResultInPlace(
            materializedResult,
            pageSize,
            checkHasNextPage,
            paginationDirection,
            out hasNextPage);
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CreateCursor(global::TestNamespace.@event data)
    {
        if (data == null)
        {
            throw new global::System.ArgumentNullException(nameof(data));
        }

        return new Cursor(data.@namespace.@namespace, data.@namespace.@event);
    }

#region IKeySetCursorSerializer implementation
    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public Cursor CursorFromString(string cursorString)
    {
        if (cursorString == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursorString));
        }

        try
        {
            var decodedString = global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Decode(cursorString);
            return global::System.Text.Json.JsonSerializer.Deserialize<Cursor>(decodedString, options: PrivateHelper.JsonOptions)
              ?? throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Deserializing '{nameof(cursorString)}' argument produced null Cursor object.");
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to decode or deserialize '{nameof(cursorString)}' argument value.", ex);
        }
    }

    /// <inheritdoc />
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public string CursorToString(Cursor cursor)
    {
        if (cursor == null)
        {
            throw new global::System.ArgumentNullException(nameof(cursor));
        }

        try
        {
            var jsonString = global::System.Text.Json.JsonSerializer.Serialize(cursor, options: PrivateHelper.JsonOptions);
            return global::Jameak.CursorPagination.Abstractions.Internal.InternalProcessingHelper.UrlSafeBase64Encode(jsonString);
        }
        catch (global::System.Exception ex)
        {
            throw new global::Jameak.CursorPagination.Abstractions.Exceptions.KeySetCursorDeserializationException($"Failed to serialize '{nameof(cursor)}' argument value.", ex);
        }
    }
#endregion

    /// <summary>
    /// Source generated Cursor holding the data necessary to paginate the
    /// TestNamespace.@event
    /// type using the fields matching this strategy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
    public sealed record Cursor : global::Jameak.CursorPagination.Abstractions.KeySetPagination.IKeySetCursor
    {
        public string _namespace__namespace { get; init; }
        public string _namespace__event { get; init; }

        public Cursor(string _namespace__namespace, string _namespace__event)
        {
            this._namespace__namespace = _namespace__namespace;
            this._namespace__event = _namespace__event;
        }
    }
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Jameak.CursorPagination.SourceGenerator", "LOCALBUILD")]
file class PrivateHelper
{
    internal const char CursorElemSeparator = ';';

    internal static int ComputeToTake(int pageSize)
    {
        checked
        {
            return pageSize + 1;
        }
    }

    internal static global::System.Linq.IOrderedQueryable<global::TestNamespace.@event> ApplyOrderBy(
        global::System.Linq.IQueryable<global::TestNamespace.@event> queryable,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderBy(queryable, (obj => obj.@namespace.@namespace));
                    orderedQueryable = global::System.Linq.Queryable.ThenBy(orderedQueryable, (obj => obj.@namespace.@event));
                    return orderedQueryable;
                }
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                {
                    var orderedQueryable = global::System.Linq.Queryable.OrderByDescending(queryable, (obj => obj.@namespace.@namespace));
                    orderedQueryable = global::System.Linq.Queryable.ThenByDescending(orderedQueryable, (obj => obj.@namespace.@event));
                    return orderedQueryable;
                }
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }

    internal static global::System.Linq.Expressions.Expression<global::System.Func<global::TestNamespace.@event, bool>>? GetWhereExpr(
        @protected.Cursor? cursor,
        global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection paginationDirection)
    {
        if(cursor == null)
        {
            return null;
        }

        var _namespace__namespaceValue = cursor._namespace__namespace;
        var _namespace__eventValue = cursor._namespace__event;

        switch (paginationDirection)
        {
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Forward:
                return obj =>
                    obj.@namespace.@namespace!.CompareTo(_namespace__namespaceValue!) >= 0
                    && (
                        (obj.@namespace.@namespace!.CompareTo(_namespace__namespaceValue!) > 0) ||
                        (obj.@namespace.@namespace!.CompareTo(_namespace__namespaceValue!) == 0 && obj.@namespace.@event!.CompareTo(_namespace__eventValue!) > 0)
                    );
            case global::Jameak.CursorPagination.Abstractions.Enums.PaginationDirection.Backward:
                return obj =>
                    obj.@namespace.@namespace!.CompareTo(_namespace__namespaceValue!) <= 0
                    && (
                        (obj.@namespace.@namespace!.CompareTo(_namespace__namespaceValue!) < 0) ||
                        (obj.@namespace.@namespace!.CompareTo(_namespace__namespaceValue!) == 0 && obj.@namespace.@event!.CompareTo(_namespace__eventValue!) < 0)
                    );
            default:
                throw new global::System.ArgumentException("Invalid pagination direction specified.", nameof(paginationDirection));
        }
    }
#region IKeySetCursorSerializer De-/serialization methods
    internal static global::System.Text.Json.JsonSerializerOptions JsonOptions { get; } = InitializeJsonOptions();

    private static global::System.Text.Json.JsonSerializerOptions InitializeJsonOptions()
    {
        var options = new global::System.Text.Json.JsonSerializerOptions
        {
            NumberHandling = System.Text.Json.Serialization.JsonNumberHandling.AllowNamedFloatingPointLiterals,
            PropertyNamingPolicy = new CursorHiddenNamePolicy(),
        };
        
        return options;
    }
#endregion
}

file class CursorHiddenNamePolicy : global::System.Text.Json.JsonNamingPolicy
{
    public override string ConvertName(string name)
    {
        return name switch
        {
            nameof(@protected.Cursor._namespace__namespace) => "0",
            nameof(@protected.Cursor._namespace__event) => "1",
            _ => throw new global::System.NotImplementedException($"Unhandled name: {name}"),
        };
    }
}
